// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN7k86WOICvEXwKIr1qgCX_dqYC_H4pL0',
    appId: '1:223002377605:web:750a8507ea89a7f77598ec',
    messagingSenderId: '223002377605',
    projectId: 'music-connections-c3536',
    authDomain: 'music-connections-c3536.firebaseapp.com',
    storageBucket: 'music-connections-c3536.appspot.com',
    measurementId: 'G-QH5E08P3LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxfcxqMSiyK7hO7_mxPuMC-cQYJv871Rg',
    appId: '1:223002377605:android:18dc1960017563b77598ec',
    messagingSenderId: '223002377605',
    projectId: 'music-connections-c3536',
    storageBucket: 'music-connections-c3536.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpzmbg7K1Tzc5eC6Ur44IDG6T6iwhgA1k',
    appId: '1:223002377605:ios:ffd07e8e6460fb437598ec',
    messagingSenderId: '223002377605',
    projectId: 'music-connections-c3536',
    storageBucket: 'music-connections-c3536.appspot.com',
    iosClientId: '223002377605-4m3tc05eqouv9l4f7k1f69fan6r82q85.apps.googleusercontent.com',
    iosBundleId: 'com.arjundev.music-connections',
  );
}
